`What is NumPy?`


NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.



`Why Use NumPy?`


In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.



`Why is NumPy Faster Than Lists?`


NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



In [5]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
print(np.__version__)

1.24.3


In [8]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
b=np.array((1,2,34,5))
print(b) # input is tuple but it converts to nd array
print(type(b)) 

[ 1  2 34  5]
<class 'numpy.ndarray'>


To create an ndarray,` we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray`

In [18]:
# 0-D Arrays
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

# here are examples of 0D, 1D, and 2D arrays using NumPy:

d=np.array(2)

d
# zero dimensional arrays


d1=np.array([1,2,3,4,5])
d1
# one dimensional arrays


# syntax for 2D is [[],[]]
d2=np.array([[1,2,3,4],(4,5,6,7)])
d2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [21]:
# 3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

# These are often used to represent a 3rd order tensor.

# Example
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:


d3=np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
d3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [26]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

d=np.array(1)
print(d.ndim)
d1=np.array([1,2,3])
print(d1.ndim)
d2=np.array([[1,2,3],[4,5,6]])
print(d2.ndim)
d3=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
print(d3.ndim)

0
1
2
3


In [27]:
d4=np.array([1,2],ndmin=6)
print(d4.ndim)

6


Access Array Elements


Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [28]:
# acess the array with is index number 

a=np.array([1,2,3])
a[0]

1

In [31]:
print(a[0]+a[2])

4


In [37]:
# Access 2-D Arrays
# To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

# Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.


d3=np.array([[1,2,3],[4,5,6]])

print(d3[0,1],d3[1,0])

2 4


Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element 


In [8]:
import numpy as np
d3=np.array([[[1,2,3],[4,5,61]],[[4,5,6],[7,8,9]]])

print(d3[0,1,2])
print(d3[-1,-1,-1])

61
9


Slicing arrays


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1


In [1]:
import numpy as np

a=np.array([1,2,3,4,5,6])
a[0:5] # start end step  end is not included in this case it is 5 but it will take as 4 or end -1

# Note: The result includes the start index, but excludes the end index.

array([1, 2, 3, 4, 5])

In [2]:
import numpy as np

a=np.array([1,2,3,4,5,6])
print(a[0:])


a=np.array([1,2,3,4,5,6])
print(a[:6])


a=np.array([1,2,3,4,5,6])
print(a[:])


a=np.array([1,2,3,4,5,6])
print(a[0:6:2])


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 3 5]


In [11]:
# negative slicing


a=np.array([1,2,3,4,5,6])
print(a[-1:-7:-1])

# for using negative it's best when you decalre the step

[6 5 4 3 2 1]


`syntax =  [start_row_index:end_row_index,start_col_index:end_col_index]`

In [62]:
import numpy as np

arr = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 0,  1,  2,  3]])
print(arr.ndim)

arr[0:3,0:4]

2


array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

In [63]:
import numpy as np

arr = np.array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 0,  1,  2,  3]])
print(arr.ndim)

arr[0:3,0:4 :2
    ]

2


array([[0, 2],
       [4, 6],
       [0, 2]])

Data Types in Python

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j




Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [67]:
import numpy as np

arr = np.array(["fdfs","sdfdfdfssd","dsfd"],dtype='S')

print(arr.dtype)

|S10


`Create an array with data type 4 bytes integer:`

In [69]:
import numpy as np

a=np.array([1,32,4,6],dtype='i4')
a.dtype

dtype('int32')

Converting Data Type on Existing Arrays


The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.


The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.


The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.


In [77]:
# type casting a var they already exist in the code 
# now convert float into int
import numpy as np

a=np.array([1.2,4.4])
anew=a.astype(int)
print(anew)
print(anew.dtype)

[1 4]
int32


In [79]:
# type casting a var they already exist in the code 
# now convert int,float into boolean
import numpy as np

a=np.array([1.2,4.4])
anew=a.astype(bool)
print(anew)
print(anew.dtype)


a=np.array([1,4])
anew=a.astype(bool)
print(anew)
print(anew.dtype)

[ True  True]
bool
[ True  True]
bool


The Difference Between Copy and View


`The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.`

The copy owns the data and any changes made to `the copy will not affect original array`, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to` the view will affect the original array`, and any changes made to the original array will affect the view.

In [86]:
import numpy as np

arr = np.array([1, 2, 3, 4])


anew=arr.copy()
anew
anew[0]=2
print(anew,arr)

# it doesn't affect the original data

[2 2 3 4] [1 2 3 4]


In [87]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


# it will affect the original data

[42  2  3  4  5]
[42  2  3  4  5]


Check if Array Owns its Data



`As mentioned above, copies owns the data, and views does not own the data, but how can we check this?`



`Every NumPy array has the attribute base that returns None if the array owns the data.`



Otherwise, the base  attribute refers to the original object.

In [88]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y=arr.copy()
arr[0] = 42

print(x.base)
print(y.base)




[42  2  3  4  5]
None



In NumPy, the shape of an array is a tuple of integers that gives the size of the array in each dimension. We can get the shape of an array using the shape attribute of the NumPy array. For example, consider the following 2D array:

In [90]:
import numpy as np 

a=np.array([[1,2,3,4],[1,2,3,4]])
print(a.shape)
#  it will print the no of row and  column

(2, 4)


In [92]:
import numpy as np 

a=np.array([[1,2,3,4],[1,2,3,4]],ndmin=3)
print(a.shape)
#  it will print the no of row and  column

(1, 2, 4)


Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

Can We Reshape Into any Shape?


Yes, as long as the elements required for reshaping are equal in both shapes.


We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but `we cannot reshape it into a 3 elements 3 rows 2D array as that would require 
3x3 = 9 elements.`



In [93]:
import numpy as np

a=np.array([1,2,3,4,5,6])

anew=a.reshape(2,3)
print(anew)

[[1 2 3]
 [4 5 6]]


In [96]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

anew=a.reshape(2,2,3)
print(anew)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [97]:
# Returns Copy or View?

import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

anew=a.reshape(2,2,3)
print(anew.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


`Flattening the arrays`

Flattening array means converting a multidimensional array into a 1D array.

`We can use reshape(-1) to do this.`



In [106]:
# convert a 2d to 1d matrix

import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
newarr=a.reshape(-1)
newarr

2


array([1, 2, 3, 4, 5, 6])

`Iterating Arrays`


Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [107]:
import numpy as np 
a=np.array([1,2,3,4,5])
# using for loop

for i in a:
    print(i)

1
2
3
4
5


In [110]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])

# for loop for 2 dimensional

for i in a :
    for j in i :
        print(j)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [114]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

# for loop for 2 dimensional

for i in a :
    for j in i :
        for k in j :
            print(k)

1
2
3
4
5
6
1
2
3
4
5
6


Iterating Arrays Using nditer()


The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.



Iterating on Each Scalar Element


In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

`this methods need one argument the name of the variable`

In [116]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

# for loop for 2 dimensional

for i in np.nditer(a) :
    print(i)

    

1
2
3
4
5
6
1
2
3
4
5
6


In [117]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [119]:
import numpy as np

a=np.array([[[1,2,3],[4,5,6]]])

# for loop for 2 dimensional

for i in np.nditer(a[:,::3]) :
    print(i)

1
2
3


Enumerated Iteration Using ndenumerate()


Enumeration means mentioning sequence number of somethings one by one.



Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

it show index as well as value of the element

In [121]:
import numpy as np
a=np.array([1,2,34,55])

for i ,j in np.ndenumerate(a):
    print(i,j)

(0,) 1
(1,) 2
(2,) 34
(3,) 55


Joining NumPy Arrays


Joining means putting contents of two or more arrays in a single array.



In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.


We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [125]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Splitting NumPy Arrays


Splitting is reverse operation of Joining.



Joining merges multiple arrays into one and Splitting breaks one array into multiple.



We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [130]:
import numpy as np
a=np.array([1,2,3,45])
newa=np.split(a,2)

newa

[array([1, 2]), array([ 3, 45])]

`Note: The return value is a list containing three arrays.`

In [135]:
a=np.array([1,2,3,4,5,6])
newa=np.array_split(a,3)
newa
for i in newa :
    print(i)


""""
The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:
"""


[1 2]
[3 4]
[5 6]


'"\nThe return value of the array_split() method is an array containing each of the split as an array.\n\nIf you split an array into 3 arrays, you can access them from the result just like any array element:\n'

Splitting 2-D Arrays


Use the same syntax when splitting 2-D arrays.


Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [140]:
# Splitting 2-D Arrays


import numpy as np

arr2 = np.array([[5, 6], [7, 8]])

newa =np.array_split(a,2)


The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

`The example below also returns three 2-D arrays, but they are split along the row (axis=1).`


In [141]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Searching Arrays


You can search an array for a certain value, and return the indexes that get a match.



To search an array, use the where() method.

In [145]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(a==10)
x

# it return the index values as well as the dtype

(array([9], dtype=int64),)

Search Sorted


There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.



`The searchsorted() method is assumed to be used on sorted arrays.`

In [147]:
import numpy as np
a=np.array([1,2,3,4,5])
x=np.searchsorted(a,3)
x
# it return the index value of the find element

2

Search From the Right Side


`By default the left most index is returned, but we can give side='right' to return the right most index instead.`



In [153]:
import numpy as np

a=([1,2,3,4,5])
x=np.searchsorted(a,3,side='left')
x

2

In [155]:
import numpy as np

a=([1,2,3,4,5,6,7,8])
x=np.searchsorted(a,[1,2,3])
x

array([0, 1, 2], dtype=int64)

Sorting Arrays


Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.



In [158]:
import numpy as np

a=np.array([9,8,7,6,5])

x=np.sort(a)
x

array([5, 6, 7, 8, 9])

In [159]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted:

In [169]:
import numpy as np
anew=np.array([[9,8,7],[1,2,3]])
x=np.sort(a)
x

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

`Filtering Arrays`


Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [171]:
import numpy as np

arr = np.array([1,2,43,5])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[ 1 43]


In [177]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10])

filt=[]

for i in a:
    if i%2==0:
        filt.append(True)
    else :
        filt.append(False)

newa=a[filt]
newa

newa


array([ 2,  4,  6,  8, 10])

In [178]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
